"""Google Maps searches that cover Armenian businesses. No niche is preferred, so the list is broad."""

import random

CATEGORIES = (
    "beauty salon",
    "barbershop",
    "nail salon",
    "cosmetology clinic",
    "dental clinic",
    "medical clinic",
    "diagnostic center",
    "pharmacy",
    "optics store",
    "veterinary clinic",
    "pet shop",
    "fitness gym",
    "yoga studio",
    "dance school",
    "language school",
    "training center",
    "kindergarten",
    "restaurant",
    "cafe",
    "coffee shop",
    "bakery",
    "pastry shop",
    "food delivery",
    "catering",
    "hotel",
    "guest house",
    "travel agency",
    "event agency",
    "wedding salon",
    "photo studio",
    "flower shop",
    "clothing store",
    "shoe store",
    "children's clothing store",
    "jewelry store",
    "cosmetics store",
    "furniture store",
    "interior design studio",
    "home appliances store",
    "electronics store",
    "mobile phone repair",
    "building materials store",
    "construction company",
    "real estate agency",
    "car service",
    "car wash",
    "auto parts store",
    "car dealer",
    "car rental",
    "logistics company",
    "courier service",
    "printing house",
    "cleaning company",
    "law firm",
    "accounting firm",
    "insurance agency",
    "online store",
    "wholesale company",
)

# Yerevan districts are listed separately: one Google query returns at most 60 places.
LOCATIONS = (
    "Kentron, Yerevan",
    "Arabkir, Yerevan",
    "Ajapnyak, Yerevan",
    "Davtashen, Yerevan",
    "Avan, Yerevan",
    "Kanaker-Zeytun, Yerevan",
    "Nor Nork, Yerevan",
    "Nork-Marash, Yerevan",
    "Erebuni, Yerevan",
    "Shengavit, Yerevan",
    "Malatia-Sebastia, Yerevan",
    "Nubarashen, Yerevan",
    "Gyumri",
    "Vanadzor",
    "Abovyan",
    "Vagharshapat",
    "Hrazdan",
    "Dilijan",
    "Kapan",
    "Armavir, Armenia",
)


def all_queries() -> list[str]:
    """Every category in every location, in a fixed shuffled order so that each day brings a mix of niches
    and districts rather than, say, only clinics. The seed keeps the order stable between restarts."""
    queries = [f"{c} in {loc}" for loc in LOCATIONS for c in CATEGORIES]
    random.Random(2026).shuffle(queries)
    return queries
